version: "3.1"

services:
  mongo:
    image: mongo:4.2.8
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=example

  # backend:
  #   build:
  #     context: .
  #     dockerfile: docker/backend/Dockerfile
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - PORT=4000
  #     - DATABASE_URL=mongodb://root:example@mongo:27017
  #   depends_on:
  #     - mongo

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: docker/frontend/Dockerfile
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules/
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PORT=3000
  #     - HOST=0.0.0.0
  #   depends_on:
  #     - mongo
  #     - backend

volumes:
  dbdata:
